### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jameswilddev** [csabahruska/demoscene#1]
Hello!  Is this project under any particular license?

Thanks,
  James.

**Comment by csabahruska** [comment]
Hi,

The code is BSD3.
https://github.com/csabahruska/demoscene/blob/master/demoscene.cabal#L7

The music is copyright to [Ficture](https://ficture.bandcamp.com/releases). We used it with permission.
https://github.com/csabahruska/demoscene/blob/master/music/license.txt

**Comment by jameswilddev** [comment]
Aha thanks, don't know how I missed that, must've been the one place I didn't look!
